import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import {dark} from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.className} h-screen antialiased`}
      >
        <ClerkProvider appearance={{
          baseTheme: dark
        }}> {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
